tap "gcenx/wine"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "shopify/shopify"
brew "openldap"
brew "freetds"
brew "libpq"
brew "sqlite"
brew "composer"
brew "deno"
brew "dnsmasq"
brew "folly"
brew "gcc"
brew "gibo"
brew "git-flow-avh"
brew "mas"
brew "python@3.10"
brew "python@3.9"
brew "ruby@3.0"
brew "subversion"
brew "watchman"
brew "shopify/shopify/shopify-cli"
cask "authy"
cask "discord"
cask "fig"
cask "firefox"
cask "fork"
cask "forklift"
cask "google-chrome"
cask "handbrake"
cask "kitty"
cask "ksdiff"
cask "maccy"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "mysqlworkbench"
cask "notion"
cask "raycast"
cask "rectangle"
cask "renamer"
cask "sequel-ace"
cask "skitch"
cask "skype"
cask "slack"
cask "steam"
cask "transmit"
cask "unofficial-wineskin"
cask "vlc"
cask "warp"
mas "Amphetamine", id: 937984704
mas "Base", id: 402383384
mas "Dashlane", id: 517914548
mas "ExSqueeze it", id: 680194796
mas "Genki Arcade", id: 1555925018
mas "Kaleidoscope", id: 587512244
mas "Tunacan", id: 980577198
mas "WinArchiver", id: 413215883
